name: tiktorch-server-env
channels:
  - ilastik-forge
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - lapack
  - mypy
  - pickle5
  - python=3.7.*
  - paramiko=2.4.2
  - pillow=6.2.1
  - pyyaml=5.3
  - marshmallow=3.4.0
  - pytest=4.3.0
  - grpcio=1.23
  - protobuf=3.11.4
  - black
  - isort
  - conda-build
  - anaconda-client
  - pre_commit
  # generic model dependency (not used by tiktorch itself)
  - scipy=1.4.*
  - inferno=v0.4.*
  # pip dependencies
  - pip
  - pip:
    - bump2version
    - pytest-grpc==0.7.0
    - git+https://github.com/bioimage-io/python-bioimage-io#egg=pybio
    - git+https://github.com/bioimage-io/pytorch-bioimage-io#egg=pybio
